### ISSUE TITLE
Getting java.lang.AssertionError when I run `lein doc` to generate codox documentation with this plugin installed

### ISSUE THREAD

**Issue by ozanvos** [ninjudd/lein-protobuf#4]
lein-protobuf itself works fine, and simply commenting `[lein-protobuf "0.3.1"]` out restores the correct behaviour of other plugins.

Might be related to `leinjacker` version lein-protobuf depends on: https://github.com/weavejester/lein-ring/issues/61

Full error:

```
Exception in thread "main" java.lang.AssertionError: Assert failed: (vector? (:dependencies project []))
    at leinjacker.deps$add_if_missing.invoke(deps.clj:43)
    at leiningen.doc$doc.invoke(doc.clj:16)
    at clojure.lang.Var.invoke(Var.java:415)
    at clojure.lang.AFn.applyToHelper(AFn.java:161)
    at clojure.lang.Var.applyTo(Var.java:532)
    at clojure.core$apply.invoke(core.clj:619)
    at leiningen.core.main$resolve_task$fn__2160.doInvoke(main.clj:148)
    at clojure.lang.RestFn.invoke(RestFn.java:410)
    at clojure.lang.AFn.applyToHelper(AFn.java:161)
    at clojure.lang.RestFn.applyTo(RestFn.java:132)
    at clojure.lang.AFunction$1.doInvoke(AFunction.java:29)
    at clojure.lang.RestFn.applyTo(RestFn.java:137)
    at clojure.core$apply.invoke(core.clj:619)
    at leiningen.core.main$apply_task.invoke(main.clj:188)
    at leiningen.core.main$resolve_and_apply.invoke(main.clj:192)
    at leiningen.core.main$_main$fn__2223.invoke(main.clj:256)
    at leiningen.core.main$_main.doInvoke(main.clj:246)
    at clojure.lang.RestFn.invoke(RestFn.java:408)
    at clojure.lang.Var.invoke(Var.java:415)
    at clojure.lang.AFn.applyToHelper(AFn.java:161)
    at clojure.lang.Var.applyTo(Var.java:532)
    at clojure.core$apply.invoke(core.clj:617)
    at clojure.main$main_opt.invoke(main.clj:335)
    at clojure.main$main.doInvoke(main.clj:440)
    at clojure.lang.RestFn.invoke(RestFn.java:436)
    at clojure.lang.Var.invoke(Var.java:423)
    at clojure.lang.AFn.applyToHelper(AFn.java:167)
    at clojure.lang.Var.applyTo(Var.java:532)
    at clojure.main.main(main.java:37)
```

**Comment by jakemcc** [comment]
Saw this same issue with another project. Had to do with lein-protobuf using an old version of leinjacker that is too restrictive on checking validity of project.clj map. Submitted a pull request. https://github.com/flatland/lein-protobuf/pull/6

I was able to get around this by excluding lein-protobuf from pulling in leinjacker. Example of what that looks like. `[lein-protobuf "0.3.1" :exclusions [leinjacker]`
